name: build static

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: copy to static repo
        env: 
          GITHUB_REPO: gitee.com/whyour/qinglong-static
        run: |
          git clone https://gitee.com/whyour/blog-static.git